// Generated by nitro

// App Config
import type { Defu } from 'defu'

import type { default as appConfig0 } from "C:/non windowa/Tec.tech/docspawn/DocSpawn/apps/docs/app.config";
import type { default as appConfig1 } from "C:/non windowa/Tec.tech/docspawn/DocSpawn/node_modules/.pnpm/@nuxt-themes+docus@1.15.0_change-case@4.1.2_nuxt@3.9.2_@parcel+watcher@2.4.0_@types+node@20.1_lyrzpxpbfjjtltlqkgz2uwzgpe/node_modules/@nuxt-themes/docus/app.config";
import type { default as appConfig2 } from "C:/non windowa/Tec.tech/docspawn/DocSpawn/node_modules/.pnpm/@nuxt-themes+typography@0.11.0_postcss@8.4.33_rollup@4.9.5_sass@1.70.0_vue@3.4.14_typescript@5.6.3_/node_modules/@nuxt-themes/typography/app.config";
import type { default as appConfig3 } from "C:/non windowa/Tec.tech/docspawn/DocSpawn/node_modules/.pnpm/@nuxt-themes+elements@0.9.5_postcss@8.4.33_rollup@4.9.5_sass@1.70.0_vue@3.4.14_typescript@5.6.3_/node_modules/@nuxt-themes/elements/app.config";

type UserAppConfig = Defu<{}, [typeof appConfig0, typeof appConfig1, typeof appConfig2, typeof appConfig3]>

declare module 'nitropack' {
  interface AppConfig extends UserAppConfig {}
}
    
export {}